# Generated by Django 6.0.6 on 2026-06-15 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dishes/')),
                ('calories_per_100g', models.PositiveIntegerField(default=0)),
                ('protein_per_100g', models.FloatField(default=0.0)),
                ('fat_per_100g', models.FloatField(default=0.0)),
                ('carbs_per_100g', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_tag', models.CharField(choices=[('slim', 'Похудение (1200-1400 ккал)'), ('balance', 'Поддержание (1600-1800 ккал)'), ('strong', 'Набор массы (2000+ ккал)')], db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Рацион',
                'verbose_name_plural': 'Рационы',
            },
        ),
        migrations.CreateModel(
            name='RationDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField()),
                ('day_number', models.PositiveSmallIntegerField(choices=[(1, 'День 1 (Понедельник)'), (2, 'День 2 (Вторник)'), (3, 'День 3 (Среда)'), (4, 'День 4 (Четверг)'), (5, 'День 5 (Пятница)')], default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ration')),
            ],
            options={
                'verbose_name': 'Блюдо в рационе',
                'verbose_name_plural': 'Блюда в рационах',
                'unique_together': {('ration', 'dish', 'day_number')},
            },
        ),
        migrations.AddField(
            model_name='ration',
            name='dishes',
            field=models.ManyToManyField(through='food.RationDish', to='food.dish'),
        ),
    ]
